= Instalação
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-09-08
:page-revdate: {revdate}

== Visão Geral

{elemental-product-name} A pilha fornece gerenciamento de SO usando contêineres OCI e Kubernetes. A instalação da pilha {elemental-product-name} abrange a instalação do {elemental_operator_name} no cluster de gerenciamento e a criação e uso de mídia de instalação para fornecer o SO aos Nós do Cluster. Veja a seção xref:rancher-os-management/architecture/architecture.adoc[Arquitetura] para ler sobre a interação dos componentes.

A configuração da instalação é aplicada e definida principalmente como parte do processo de registro.
O processo de registro é realizado pelo `elemental-register` (a parte cliente do {elemental_operator_name}) que é responsável por registrar nós em um cluster de gerenciamento Rancher e buscar a configuração da instalação.

Por favor, consulte o guia xref:quickstarts/quickstart-cli.adoc[Início Rápido] para instruções simples de implantação passo a passo.

== {elemental-product-name} Instalação do Operador

O {elemental_operator_name} é responsável por gerenciar as versões do {elemental-product-name} e por manter um inventário de máquinas para auxiliar em instalações edge ou bare metal. {elemental_operator_name} requer um cluster que inclua o Rancher Manager e pode ser instalado com um Helm chart.

Veja {elemental_operator_name} xref:references/operatorchart-reference.adoc[referência do Helm chart] para detalhes de instalação, desinstalação, upgrade e configuração.

== Prepare Recursos do Kubernetes

Uma vez que o {elemental_operator_name} esteja em funcionamento dentro do cluster de gerenciamento, alguns recursos do Kubernetes são necessários para preparar uma implantação de cluster baseada em {elemental-product-name}.

* xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate]:
Este recurso identifica os critérios para corresponder caixas registradas (listadas como parte do MachineInventory) contra Clusters Rancher 2.6 disponíveis. Assim que houver uma correspondência, o cluster kubernetes selecionado assume a propriedade da caixa registrada.
* xref:references/machineregistration-reference.adoc[MachineRegistration]:
Este recurso define os detalhes da implantação do SO para qualquer máquina que esteja tentando se registrar. O registro da máquina é a entrada para nós {elemental-product-name}, pois lida com a autenticação (baseada em TPM), a implantação do SO e a inclusão do nó no MachineInventory para que possa ser adicionado a um cluster quando houver uma correspondência com base em um MachineInventorySelectorTemplate. O objeto MachineRegistration inclui a URL de registro da máquina que os nós usam para se registrar.

Um recurso de Cluster Rancher também é necessário para implantar {elemental-product-name}, ele pode ser criado manualmente como exemplificado no guia xref:quickstarts/quickstart-cli.adoc[Início Rápido] ou criado a partir da interface do usuário do Rancher 2.6.

== Prepare a Mídia de Instalação

A mídia de instalação é a mídia que será usada para iniciar a implantação de um sistema operacional. Atualmente, a mídia suportada é uma ISO ao vivo. A ISO ao vivo deve incluir a configuração de registro em yaml, portanto, deve ser elaborada assim que o registro da máquina for criado. A mídia de instalação é gerada criando recursos de xref:references/seedimage-reference.adoc[Imagem Semente] (veja xref:quickstarts/quickstart-cli.adoc#_preparing_the_installation_seed_image[Início Rápido] e xref:operator-operational-tasks/custom-images.adoc#_create_a_custom_bootable_installation_iso[imagens personalizadas]).

A ISO ao vivo suporta Inicialização PXE para integração direta com https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/autoinst-distributions.html#based-on-iso-image[Gerenciador SUSE].

Dentro do registro da máquina, apenas um subconjunto de parâmetros de instalação do sistema operacional pode ser configurado; todos os parâmetros disponíveis estão listados na página de referência xref:references/machineregistration-reference.adoc[Registro da Máquina].

Para configurar a instalação além das opções comuns fornecidas na seção xref:references/machineregistration-reference.adoc#_config_elemental_install[`elemental.install`], pode-se incluir um arquivo de configuração `config.yaml` na ISO (veja xref:installation/customize-installation/custom-install.adoc#_custom_suse_rancher_prime_os_manager_client_configuration_file[Imagens Personalizadas]).
Observe que qualquer configuração aplicada como parte da seção `elemental.install` do Registro da Máquina será aplicada sobre as configurações incluídas em qualquer arquivo `config.yaml` personalizado.

Provavelmente, a configuração do cloud-init é suficiente para configurar e definir o nó implantado na inicialização; no entanto, se por algum motivo ações ou scripts de primeira inicialização forem necessários, também é possível incluir planos do Agente de Sistema Rancher na mídia de instalação. Consulte a seção xref:rancher-os-management/plans.adoc[Planos] para detalhes e alguns planos de exemplo. Os planos podem ser incluídos no rootfs compactado na pasta `/var/lib/elemental/agent/plans` e serão vistos pelo agente do sistema na primeira inicialização.

== Iniciar o Processo de Instalação

A instalação começa inicializando a mídia de instalação em um nó. Uma vez que a mídia de instalação tenha inicializado, ela tentará contatar o cluster de gerenciamento e se registrar nele chamando o comando `elemental-register`.
Como a configuração yaml de registro já está incluída na ISO, `elemental-register` conhece a URL de registro e quaisquer outros dados necessários para o registro.

Com um registro bem-sucedido, a mídia de instalação iniciará a instalação no host com base na configuração já incluída na mídia e nos parâmetros do registro da máquina. Assim que a instalação estiver concluída, o nó estará pronto para reiniciar. O sistema operacional implantado inclui um plano de agente de sistema para iniciar um processo regular de provisionamento do Rancher para instalar a versão do Kubernetes selecionada; uma vez inicializado, após alguns minutos, a instalação do nó é finalizada e o nó é incluído no cluster e visível através da UI do Rancher.

== Tabela de Partição Implantada

Uma vez que o sistema operacional esteja instalado, a tabela de partição do SO, de acordo com os valores padrão, ficará assim:

|===
| Etiqueta | Tamanho padrão | Contém

| COS_GRUB
| 64 MiB
| Partição de boot UEFI

| COS_STATE
| 8 GiB
| Imagens de sistema de arquivos de boot A/B construídas a partir de imagens OCI

| COS_OEM
| 64 MiB
| Arquivos de configuração de nuvem OEM e outros dados

| COS_RECOVERY
| 4 GiB
| Imagem de sistema de arquivos de recuperação se COS_ESTADO for destruído

| COS_PERSISTENT
| Espaço restante
| Todo o conteúdo das pastas persistentes
|===

Observe que esta é a estrutura básica de qualquer sistema operacional construído pelo {elemental_toolkit_url}[{elemental_toolkit_name}].

== {elemental-product-name} Raiz Imutável

Uma das características dos sistemas operacionais {elemental-product-name} é a configuração de um sistema de arquivos raiz imutável onde alguns locais efêmeros ou persistentes são aplicados sobre ele. A estrutura padrão das pastas está listada na matriz abaixo.

[cols=",^,^,^"]
|===
| Caminho | Apenas Leitura | Efêmero | Persistente

| /
| x
|
|

| /etc
|
| x
|

| /etc/cni
|
|
| x

| /etc/iscsi
|
|
| x

| /etc/rancher
|
|
| x

| /etc/ssh
|
|
| x

| /etc/systemd
|
|
| x

| /srv
|
| x
|

| /home
|
|
| x

| /opt
|
|
| x

| /root
|
|
| x

| /var
|
| x
|

| /usr/libexec
|
|
| x

| /var/lib/cni
|
|
| x

| /var/lib/kubelet
|
|
| x

| /var/lib/rancher
|
|
| x

| /var/lib/elemental
|
|
| x

| /var/lib/NetworkManager
|
|
| x

| /var/lib/calico
|
|
| x

| /var/log
|
|
| x
|===
