== Machine onboarding

The goal of the Machine Onboarding service is to register a new machine in the Elemental Operator catalog (xref:machineinventory-reference.adoc[MachineInventory] resources) and provision the host with the OS, applying the desired configuration.

The Machine Onboarding involves the following steps:

* The user creates a xref:machineregistration-reference.adoc[MachineRegistration] resource: the MachineRegistration includes the configuration required for the OS installation.
As soon as the MachineRegistration is created, the Elemental Operator exposes an HTTP _registration endpoint_: it is the entrypoint required by the onboarding hosts to register to the operator.
* The user requests a self-installing image via a xref:seedimage-reference.adoc[SeedImage] resource: it only requires a reference to a MachineRegistration resource and to an OS container image compatible with the Elemental Toolkit.
As soon as the SeedImage is created, the Elemental Operator triggers the build process of the self-installing image: once completed, the URL is exposed in the `status.downloadURL` field of the xref:seedimage-reference.adoc[SeedImage] resource.
* The user downloads the self-installing image and uses it to boot an unprovisioned host:
the host https://elemental.docs.rancher.com/authentication[authenticates] to the _registration endpoint_ of the Elemental Operator, gets the full configuration stored in the MachineRegistration and installs the OS on the local storage device. As soon as the host has completed the registration process, the Elemental Operator creates a unique xref:machineinventory-reference.adoc[MachineInventory] resource tracking the host.
The self-installing image can be used to onboard any number of hosts.
