= ManagedOSVersion参考
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-09-08
:page-revdate: {revdate}

`ManagedOSVersion`资源负责定义可以与`SeedImage`或`ManagedOSImage`资源一起使用的操作系统映像版本。

在`ManagedOSVersion`资源规范下可以配置多个键。

.managedosversion-example.yaml
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  labels:
    elemental.cattle.io/channel: elemental-channel
  name: v2.0.2
  namespace: fleet-default
spec:
  metadata:
    displayName: SLE Micro
    upgradeImage: registry.suse.com/suse/sle-micro/5.5:2.0.2
  type: container
  version: v2.0.2
----

== `ManagedOSVersionSpec`参考

|===
| 键 | 类型 | 默认值 | 说明

| metadata
| 对象
| null
| 这定义了一些关于操作系统映像的数据。请参见[参考](#metadata)

| minVersion
| 字符串
| null
| 未用

| type
| 字符串
| 空
| 定义操作系统映像类型，可以是`container`或`iso`

| version
| 字符串
| 空
| 操作系统映像版本

| upgradeContainer
| 对象
| null
| 可以定义的升级容器。请参见[参考](#upgradecontainer)
|===

.点击这里查看详细信息
[%collapsible]
====
.ISO 映像示例
[,yaml]
----
metadata:
  displayName: SLE Micro ISO x86_64
  uri: registry.suse.com/suse/sl-micro/6.0/baremetal-iso-image:2.2.0
type: iso
version: v2.2.0
----
====

.点击这里查看详细信息
[%collapsible]
====
.容器映像示例
[,yaml]
----
metadata:
  displayName: SLE Micro upgrade
  upgradeImage: registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:2.2.0
type: container
version: v2.2.0
----
====

== metadata

这描述了在{elemental-product-name}中定义操作系统映像所需的信息。

如果`type`设置为`container`：

|===
| 键 | 类型 | 默认值 | 说明

| displayName
| 字符串
| 空
| 在Rancher UI中看到的操作系统映像名称

| upgradeImage
| 字符串
| 空
| 完全合格的容器映像（OCI引用或HTTP URI）
|===

如果`type`设置为`iso`：

|===
| 键 | 类型 | 默认值 | 说明

| displayName
| 字符串
| 空
| 在Rancher UI中看到的操作系统映像名称

| uri
| 字符串
| 空
| 完全合格的ISO 映像
|===

== `upgradeContainer`

这允许根据此ManagedOSVersion覆盖Upgrade Controller计划的默认`upgrade`字段（请参见xref:rancher-os-management/upgrade-lifecycle.adoc#_components[upgrade components]）。
这些键由Upgrade Controller翻译为Kubernetes https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container[容器]规范。
这是负责运行操作系统升级的容器。
