= Personnaliser le nom d'hôte
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-09-08
:page-revdate: {revdate}

== {elemental-product-name} aperçu de la gestion des noms d'hôte

Lorsqu'un hôte démarre à partir de l'ISO {elemental-product-name}, le nom d'hôte est temporairement défini (_nom d'hôte transitoire_) sur celui fourni par le serveur DHCP.
Si le serveur DHCP ne fournit pas de nom d'hôte, l'ISO {elemental-product-name} fournit un nom d'hôte transitoire sous la forme : `rancher-$\{RANDOM}`.

Dès que le processus de démarrage est terminé, la phase d'enregistrement commence : l'hôte se connecte à l'Opérateur {elemental-product-name}, qui crée un `MachineInventory` pour l'hôte.
Chaque hôte enregistré auprès de l'Opérateur {elemental-product-name} est suivi par une ressource `MachineInventory`.

*Le `name` de la ressource `MachineInventory` associée au nœud est le nom d'hôte permanent (statique)* *finalement défini pour l'hôte*.
Ce nom d'hôte permanent *est défini sur le nœud uniquement pendant la phase de provisionnement du cluster K8s*.
Avant la phase de provisionnement K8s, le nom d'hôte du nœud est soit celui attribué par le DHCP, soit `rancher-$\{RANDOM}`.

Pour le reste de cette section, nous nous référerons au `hostname` signifiant le _permanent_ nom d'hôte, c'est-à-dire, le nom d'hôte qui est défini après que l'hôte a été provisionné dans le cadre d'un cluster K8s.

== Nom d'hôte par défaut

Le nom par défaut attribué à chaque MachineInventory nouvellement créé est sous la forme `m-{$UUID}`.
Lorsque l'hôte est provisionné dans le cadre d'un Cluster, ce nom `m-\{UUID}` est défini comme le nom d'hôte de l'hôte correspondant, remplaçant le nom d'hôte précédemment attribué (`rancher-{$RANDOM}` ou celui attribué par le DHCP).

== Définir un nom d'hôte personnalisé

Le nom d'hôte peut être spécifié en définissant le champ xref:references/machineregistration-reference.adoc#_machinename[`machineName`] dans la ressource xref:references/machineregistration-reference.adoc['MachineRegistration'].

Le nom d'hôte défini dans le champ `machineName` doit être sous une forme de modèle, afin d'être généré de manière unique pour chaque nœud en cours d'enregistrement, en utilisant les données SMBIOS et les étiquettes matérielles.

[IMPORTANT]
====
Le champ `machineName` dans la ressource `MachineRegistration` est utilisé comme le plan non seulement pour le nom d'hôte de l'hôte en cours d'enregistrement, mais aussi pour le nom de la ressource `MachineInventory` créée pour suivre l'hôte.

Cela signifie que si vous n'utilisez pas un `machineName` sous forme de modèle pour générer un nom unique pour chaque hôte qui démarrera en utilisant les mêmes données `MachineRegistration` (c'est-à-dire, le même ISO), seul le premier hôte en cours d'enregistrement réussira tandis que les autres échoueront : le nom `MachineInventory` doit être unique.
====


import Registration from "!!raw-loader!@site/examples/quickstart/registration-hardware-dhcphostname.yaml"

== Conservez le nom d'hôte attribué par le DHCP

Pour conserver le nom d'hôte attribué par le serveur DHCP avant que l'hôte ne s'enregistre auprès de l'opérateur, le `MachineRegistration` xref:references/machineregistration-reference.adoc#_machinename[`machineName field`] doit être défini sur l'étiquette matérielle `${System Data/Runtime/Hostname}`.

De cette manière, {elemental-product-name} utilisera le nom d'hôte actuel comme nom `MachineInventory` pendant la phase d'enregistrement, qui sera ensuite défini comme le nom d'hôte statique de l'hôte pendant la phase de provisionnement.

include::example$quickstart/registration-hardware-dhcphostname.adoc[]
