= Referência do MachineInventorySelectorTemplate
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-09-08
:page-revdate: {revdate}

O MachineInventorySelectorTemplate é um recurso definido pelo usuário que será usado como o modelo para criar os xref:references/machineinventoryselector-reference.adoc[MachineInventorySelectors] necessários.

É o recurso responsável por definir os critérios de correspondência para emparelhar uma máquina inventariada com um recurso de Cluster.

A chave relevante é o `selector`, que inclui expressões de seletor de rótulo.

.MachineInventorySelectorTemplate
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: my-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        ...
----

`template.spec.selector` pode incluir as chaves `matchLabels` e/ou `matchExpressions`.

== `template.spec.selector.matchLabels`

É um mapa de `{key,value}` pares `(map[string]string)`. Quando múltiplos rótulos são fornecidos, todos os rótulos devem corresponder.

.Clique aqui para detalhes.
[%collapsible]
====
[yaml]
----
...
spec:
  template:
    spec:
      selector:
        matchLabels:
          element: fire
          manufacturer: somevalue
----
====

Um Cluster definido com o seletor acima só tentará provisionar nós inventariados incluindo esses dois rótulos.

== `template.spec.selector.matchExpressions`

É uma lista de seletores de rótulo, cada seletor de rótulo pode ser definido como:

|===
| Chave | Tipo | Descrição

| key
| string
| Esta é a chave de rótulo na qual o seletor se aplica

| operator
| string
| Representa a relação da chave com um conjunto de valores. Os operadores válidos são 'In', 'NotIn', 'Exists' e 'DoesNotExist'

| valores
| []string
| Valores é um array de valores de string. Se o operador for 'In' ou 'NotIn', o array de valores deve ser não vazio. Se o operador for 'Exists' ou 'DoesNotExist', o array de valores deve estar vazio.
|===

.Clique aqui para detalhes.
[%collapsible]
====
[,yaml]
----
...
spec:
  template:
    spec:
      selector:
        matchExpressions:
        - key: element
          operator: In
          values: [ 'fire' ]
        - key: manufacturer
          operator: Exists
----
====

Um Cluster definido com o seletor acima só tentará provisionar nós inventariados com o rótulo `element=fire` e incluindo um rótulo `manufacturer` definido com qualquer valor.
