= Referencia de SeedImage
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-09-08
:page-revdate: {revdate}


Un `SeedImage` recurso permite construir un medio de instalaciĂ³n que se puede utilizar para instalar {elemental-product-name} en un nodo.

Requiere un `baseImage`, es decir, una URL a una ISO de instalaciĂ³n de {elemental-product-name} o una imagen de contenedor de nodo, y una `registrationRef` referencia a un recurso `MachineRegistration`, del cual se extrae la parte de registro de la configuraciĂ³n de {elemental-product-name} y se inyecta en el medio para producir la _imagen de semilla_ final.

TambiĂ©n es posible inyectar personalizaciones en el campo `cloud-config`. Se admiten tanto la sintaxis de yip como la de cloud-init. Consulta la xref:references/cloud-config-reference.adoc[Referencia de ConfiguraciĂ³n de Nube] para obtener informaciĂ³n completa.

Una vez que la imagen de semilla estĂ¡ lista, la URL de descarga se comparte en el campo `.status.downloadURL`.
Permanece disponible para descarga durante `cleanupAfterMinutes` minutos (el valor predeterminado es `60`, 1 hora), despuĂ©s de lo cual se elimina.

Configurar `retriggerBuild` a `true` reactiva el proceso de construcciĂ³n de la imagen de semilla, mientras que configurar `cleanupAfterMinutes` a `0` mantiene la imagen de semilla hasta que se elimine el recurso `SeedImage`.

El recurso `SeedImage` tambiĂ©n tiene un campo `type` que se puede establecer en `iso`, para construir una ISO, o en `raw` para construir una imagen de disco en bruto. Las imĂ¡genes de disco en bruto se pueden copiar directamente en la unidad de destino y, en el primer arranque, se iniciarĂ¡n automĂ¡ticamente en una particiĂ³n de recuperaciĂ³n para expandir la unidad y utilizar el espacio disponible en disco y registrar el nodo, despuĂ©s de lo cual se reiniciarĂ¡ de la misma manera que para la instalaciĂ³n ISO.

Si no se especifica ningĂºn `BuildContainer` para la imagen de semilla, se rellenarĂ¡ automĂ¡ticamente en funciĂ³n de los valores predeterminados y `type`.

Construir una SeedImage para una plataforma diferente se logra utilizando el campo `targetPlatform`. La plataforma se especifica utilizando `os/arch`, por ejemplo (`linux/x86_64` o `linux/aarch64`). Por defecto, la imagen se construirĂ¡ para la misma plataforma en la que se aloja el operador.

[CAUTION]
.Las imĂ¡genes de semilla pueden llenar el almacenamiento local.
====
Las imĂ¡genes de semilla se mantienen en el almacenamiento local del nodo: presta atenciĂ³n al nĂºmero de recursos `SeedImage` que inicias de forma concurrente y a los que puedes dejar alrededor con la funciĂ³n de limpieza automĂ¡tica desactivada (`cleanupAfterMinutes` = `0`) ya que puedes agotar el almacenamiento en los nodos de tu clĂºster.
====

[#_seedimagespec_reference]
== Referencia de SeedImageSpec

|===
| Key | Tipo | Valor por defecto | DescripciĂ³n

| imagenBase
| cadena
| vaciar
| La imagen Elemental base utilizada para construir la imagen de semilla.

| registrationRef
| referencia de objeto.
| null
| Una referencia a un MachineRegistration que se utilizarĂ¡ para registrar todas las mĂ¡quinas instaladas.

| buildContainer
| object
| null
| Configuraciones para un contenedor personalizado utilizado para generar la imagen descargable. (Ver <<_buildcontainer,documentaciĂ³n>>).

| cleanupAfterMinutes
| int
| 60
| El tiempo despuĂ©s del cual se limpiarĂ¡ la imagen de semilla construida. Las descargas activas finalizarĂ¡n antes de que se elimine la imagen.

| repetirConstrucciĂ³n
| bool
| false
| Disparador para construir de nuevo una imagen de semilla limpiada.

| tamaĂ±o
| cadena
| 6Gi
| Especifica el tamaĂ±o del volumen utilizado para almacenar la imagen.

| tipo
| cadena
| iso
| Especifica el tipo de imagen de semilla a construir. `iso` o `raw`. (Ver <<_iso_and_raw_images,documentaciĂ³n>>)

| targetPlatform
| cadena
| vaciar
| Especifica la plataforma objetivo para la imagen construida. Ejemplo: `linux/x86_64` o `linux/aarch64`. (Ver <<_multi_platform_support,documentaciĂ³n>>).

| cloud-config
| object
| null
| Contiene datos de cloud-config que se incluirĂ¡n en la imagen generada. (Ver xref:references/cloud-config-reference.adoc[documentaciĂ³n]).

|===

=== BuildContainer

Los ajustes de `buildContainer` se pueden utilizar para personalizar el contenedor init `build` dentro del pod del `SeedImage`.
Este podrĂ­a ser el caso, por ejemplo, al construir imĂ¡genes Elemental personalizadas.

[,yaml]
----
buildContainer:
  name: "custom-build"
  image: my.registry.com/elemental-custom-builder:1.2.3
  command:
    - build-image
  args:
    - foo
    - bar
  imagePullPolicy: Always
----

Ten en cuenta que el contenedor tambiĂ©n tendrĂ¡ dos volĂºmenes montados en `/iso` y `/overlay`.
El proceso de construcciĂ³n de SeedImage espera que el contenedor de construcciĂ³n coloque el artefacto de construcciĂ³n en `/iso/$(ELEMENTAL_OUTPUT_NAME)`.

Los archivos de configuraciĂ³n estĂ¡n disponibles en:

- `/overlay/reg/livecd-cloud-config.yaml`: Un archivo de configuraciĂ³n que puede ser utilizado por `elemental-register` para registrar la mĂ¡quina.

- `/overlay/iso-config/cloud-config.yaml`: El cloud-config definido en `SeedImage.spec.cloud-config`

La siguiente lista de variables de entorno tambiĂ©n puede ser utilizada dentro del contenedor de construcciĂ³n personalizado:

- `ELEMENTAL_DEVICE`: El valor de `MachineRegistration.spec.config.elemental.install.device`.
- `ELEMENTAL_REGISTRATION_URL`: La URL Ăºnica de la MachineRegistration.
- `ELEMENTAL_BASE_IMAGE`: La imagen base definida en `SeedImage`.
- `ELEMENTAL_OUTPUT_NAME`: El nombre de archivo esperado del artefacto de construcciĂ³n.

[#_iso_and_raw_images]
=== ImĂ¡genes ISO y Raw

El `SeedImage` es capaz de construir tipos de imagen `iso` o `raw`.
Ten en cuenta que Elemental envĂ­a dos sabores diferentes de imĂ¡genes, tipos `iso` o `container`. Consulta xref:references/managedosversion-reference.adoc#_managedosversionspec_reference[tipo de versiĂ³n de ManagedOS].

Al construir un `iso` `SeedImage`, puedes utilizar una imagen Elemental `iso`. Las imĂ¡genes `iso` contienen un artefacto `.iso` preconstruido. Esta es la forma predeterminada de Elemental para enviar ISOs oficiales, de modo que no necesiten ser reconstruidas cada vez que defines un `SeedImage`.

.Haz clic aquĂ­ para un ejemplo de ISO SeedImage
[%collapsible]
====
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-iso
  namespace: fleet-default
spec:
  type: iso
  baseImage: registry.suse.com/suse/sl-micro/6.0/baremetal-iso-image:2.1.1-3.36
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: fire-nodes
    namespace: fleet-default
----
====

Alternativamente, al construir un `raw` `SeedImage`, deberĂ­as utilizar imĂ¡genes Elemental `container`. Estas imĂ¡genes tambiĂ©n se utilizan durante el proceso de actualizaciĂ³n (Consulta: xref:references/managedosimage-reference.adoc[ManagedOSImage]), pero tambiĂ©n pueden ser utilizadas para construir `raw` `SeedImages`.

.Haz clic aquĂ­ para el ejemplo de Raw SeedImage
[%collapsible]
====
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-raw
  namespace: fleet-default
spec:
  type: raw
  baseImage: registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:2.1.1-3.29
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: fire-nodes
    namespace: fleet-default
----
====

[#_multi_platform_support]
=== Compatibilidad con diversas plataformas

Elemental distribuye imĂ¡genes `linux/x86_64` y `linux/aarch64` para la mayorĂ­a de las versiones.
Para determinar si una imagen `ManagedOSVersion` es compatible con ambas plataformas, puedes verificar los valores de `ManagedOSVersion.spec.metadata.platform`. (Consulta xref:references/managedosversion-reference.adoc#_metadata[documentaciĂ³n]).

Al definir un `SeedImage`, puedes usar este valor para el `targetPlatform` de la imagen.
Dejar el `targetPlatform` vacĂ­o, se ajustarĂ¡ a la plataforma donde se estĂ© ejecutando el `elemental-operator`.

.Haz clic aquĂ­ para el ejemplo de Raw aarch64 SeedImage
[%collapsible]
====
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-raw-aarch64
  namespace: fleet-default
spec:
  targetPlatform: linux/aarch64
  type: raw
  baseImage: registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:2.1.1-3.29
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: fire-nodes
    namespace: fleet-default
----
====

== URLs descargables

El recurso `SeedImage` rastrea el proceso de construcciĂ³n de la imagen semilla a travĂ©s de dos condiciones de estado:

- **Ready**: rastrea la creaciĂ³n de todos los recursos secundarios necesarios que realizan el proceso de construcciĂ³n real.
- **SeedImageReady**: rastrea el estado del proceso de construcciĂ³n en los recursos secundarios.

Alternativamente, tambiĂ©n es posible esperar a que el pod `SeedImage` estĂ© listo:

[,bash]
----
kubectl wait --for=condition=ready pod -n fleet-default fire-img
----

Esperar las condiciones de Ready es una buena prĂ¡ctica antes de descargar cualquier artefacto.

Una vez que un `SeedImage` estĂ© listo, el `.status.downloadURL` contendrĂ¡ la URL descargable.
Ten en cuenta que la URL utilizarĂ¡ el mismo punto final que Rancher, asĂ­ que ten cuidado con la validaciĂ³n HTTPS al usar certificados autofirmados.

[,bash]
----
kubectl get seedimage -n fleet-default fire-img -o jsonpath="{.status.downloadURL}"
----

La suma de comprobaciĂ³n de la imagen tambiĂ©n estĂ¡ disponible para verificar que la descarga fue correcta:

[,bash]
----
kubectl get seedimage -n fleet-default fire-img -o jsonpath="{.status.checksumURL}"
----