= Inventarverwaltung
:revdate: 2025-08-15
:page-revdate: {revdate}

Der {elemental-product-name} Operator kann ein Inventar von Maschinen halten und die Zuordnung der Maschine zu ihrer Konfiguration und dem zugewiesenen Cluster.

== MachineInventory

Der `MachineInventory` enthält alle relevanten Informationen für eine registrierte Maschine. +
Nach erfolgreicher Registrierung wird der `MachineInventory` alle `machineInventoryLabels` erben, die im zugehörigen `MachineRegistration` definiert sind. +
Zusätzlich wird die Maschine `annotations` bei jeder erfolgreichen Registrierung ebenfalls aktualisiert.

Standardmäßig versuchen {elemental-product-name} Maschinen, alle 24 Stunden eine Registrierungsaktualisierung durchzuführen, um Labels und Annotationen zu aktualisieren.

=== Kurz nachgeschlagen

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  # Machine annotations can be useful to identify hosts
  annotations:
    elemental.cattle.io/auth: tpm
    elemental.cattle.io/registration-ip: 192.168.122.152
  labels:
    # A label inherited from the MachineRegistration definition
    element: fire
    # Generic SMBIOS labels that are typically populated with
    # the MachineRegister approach
    machineUUID: f266c64b-3972-40e7-9937-3dc4a311436c
    manufacturer: QEMU
    productName: Standard-PC-Q35-ICH9-2009
    serialNumber: Not-Specified
    # Custom labels can be applied to each MachineInventory
    myCustomLabel: foo
  name: m-479ab68e-00ff-4081-a731-5b1a76610289
  # The namespace must match the namespace of the cluster
  # assigned to the clusters.provisioning.cattle.io resource
  namespace: fleet-default
  # A reference to the MachineInventorySelector that links the
  # machine to a Cluster definition
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: MachineInventorySelector
    name: fire-machine-selector-qcn7d
    uid: 0a1f751e-4ca9-4a0d-919a-97ba1f434d12
spec:
  # The hash of the TPM EK public key. This is used if you are
  # using TPM2 to identify nodes. Nodes can report their TPM
  # hash by using the MachineRegistration.
  tpmHash: d68795c6192af9922692f050b...
----

== MachineRegistration

`MachineRegistration` enthält Informationen darüber, wie man alle verbundenen {elemental-product-name} Maschinen installiert, zurücksetzt und konfiguriert.

Es ist möglich, den `spec.machineInventoryLabels` und `spec.machineInventoryAnnotations` zu aktualisieren, und dies wird auf alle registrierten Maschinen angewendet.
Standardmäßig versuchen {elemental-product-name} Maschinen, alle 24 Stunden eine Registrierungsaktualisierung durchzuführen, um Labels und Annotationen zu aktualisieren.

Obwohl es möglich ist, die `spec.config` Definition zu ändern, werden Aktualisierungen an der `spec.config` von Maschinen, die die Installation bereits abgeschlossen haben, ignoriert.
Maschinen, die die Installation nicht abschließen konnten, werden alle 30 Minuten erneut versuchen, die entfernte `MachineRegistration` Definition zu laden. Dies kann nützlich sein, um `spec.config` Fehler zu korrigieren, die eine erfolgreiche Installation verhindern (z. B. `spec.config.elemental.install.device`), ohne eine neue `MachineRegistration` und ein neues ISO erstellen zu müssen.

=== Kurz nachgeschlagen

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  # The namespace must match the namespace of the cluster
  # assigned to the clusters.provisioning.cattle.io resource
  namespace: fleet-default
spec:
  # The cloud config that will be used to provision the node
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
      reset:
        enabled: true
        debug: true
        reset-persistent: true
        reset-oem: true
        reboot: true
  # Labels to be added to the created MachineInventory object
  machineInventoryLabels:
    element: fire
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
  # Annotations to be added to the created MachineInventory object
  machineInventoryAnnotations: {}
----
