= Referenz fĂĽr ManagedOSVersionChannel
:revdate: 2025-09-08
:page-revdate: {revdate}

Die `ManagedOSVersionChannel`-Ressource ist dafĂĽr verantwortlich, den OS-Image-Kanal zu definieren.

Es gibt mehrere SchlĂĽssel, die unter einer `ManagedOSVersionChannel`-Ressourcenspezifikation konfiguriert werden kĂ¶nnen.

.managedosversionchannel-example.yaml
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-channel
  namespace: fleet-default
spec:
  options:
    image: registry.suse.com/rancher/elemental-channel:1.4.2
  syncInterval: 1h
  type: custom
----

== `ManagedOSVersionChannelSpec` Referenz

|===
| Tasten | Typ | Standardwert | Beschreibung

| Optionen
| object
| null
| Definiert die optionalen Informationen, die in einem OS-Kanal hinzugefĂĽgt werden kĂ¶nnen.

| syncInterval
| Zeichenfolge
| 1h
| Definiert, wann der OS-Kanal synchronisiert werden soll.

| type
| Zeichenfolge
| Leeren
| Definiert den Kanaltyp, derzeit wird nur `custom` unterstĂĽtzt.

| upgradeContainer
| object
| null
| Ein Upgrade-Container, der definiert werden kann. Siehe <<_upgradecontainer,Referenz>>

| deleteNoLongerInSyncVersions
| bool
| false
| Automatisches LĂ¶schen auslaufender OS-Versionen, die nicht mehr im Kanal enthalten sind.

| Aktiviert
| bool
| true
| Aktiviert diesen Kanal. ErmĂ¶glicht die Synchronisierung von OS-Versionen.
|===

== `upgradeContainer`

Dies ermĂ¶glicht das Ăśberschreiben des Standardfelds `upgrade` der System Upgrade Controller-PlĂ¤ne (siehe xref:rancher-os-management/upgrade-lifecycle.adoc#_components[Upgrade-Komponenten]) basierend auf dieser ManagedOSVersion.
Diese SchlĂĽssel werden vom System Upgrade Controller in eine Kubernetes https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container[Container]-Spezifikation ĂĽbersetzt.
Dies ist der Container, der fĂĽr die DurchfĂĽhrung eines OS-Upgrades verantwortlich ist.
