= {elemental-product-name} Soporte
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-03
:page-revdate: {revdate}

El `elemental-support` es un programa de utilidad que recopila toda la información sobre la máquina donde se está ejecutando el stack {elemental-product-name}.

Al solucionar problemas con cualquier {elemental-product-name} nodo, es posible generar un archivo comprimido que contenga registros y archivos de configuración. +
Ten en cuenta que *el archivo tar.gz generado puede contener información sensible*, como tokens de acceso al clúster de gestión y más.

== Requisitos

Opcionalmente, la utilidad `elemental-support` necesita que `kubectl` esté disponible en la máquina de destino, para poder recopilar información del nodo. Esto puede ser muy útil para borrar problemas al actualizar la versión de {elemental-product-name} en un nodo. +
La configuración de kubectl utilizada se buscará en la variable de entorno `KUBECONFIG`, o en su ausencia se utilizarán los archivos `/etc/rancher/k3s/k3s.yaml` o `/etc/rancher/rke2/rke2.yaml`.

== Recopilando información

Una vez ejecutado, el `elemental-support` creará el archivo comprimido en el mismo directorio.

Ejemplo de ejecución:

[,bash]
----
m-993369ec-4b3f-4368-86c3-1449ebf57cf2# elemental-support
I0430 11:33:38.934777    8536 log.go:42] Support version 1.3.4, commit 192dc33d, commit date 20230831
I0430 11:33:38.934865    8536 log.go:46] Getting elemental-support version
I0430 11:33:38.934918    8536 log.go:42] Copying /etc/os-release
I0430 11:33:38.935008    8536 log.go:42] Copying /etc/resolv.conf
I0430 11:33:38.935066    8536 log.go:42] Copying /etc/hostname
I0430 11:33:38.935131    8536 log.go:42] Copying /etc/rancher/agent/config.yaml
I0430 11:33:38.935174    8536 log.go:42] Copying /etc/rancher/agent/config.yaml
I0430 11:33:38.935214    8536 log.go:42] Copying dir /var/lib/elemental/agent/applied/
I0430 11:33:38.935434    8536 log.go:42] Copying dir /var/lib/rancher/agent/applied/
I0430 11:33:38.935572    8536 log.go:42] Copying dir /system/oem
I0430 11:33:38.936584    8536 log.go:42] Copying dir /oem/
I0430 11:33:38.937121    8536 log.go:42] Getting service log elemental-system-agent
I0430 11:33:38.959813    8536 log.go:42] Getting service log rancher-system-agent
I0430 11:33:38.979271    8536 log.go:42] Getting service log k3s
I0430 11:33:39.018177    8536 log.go:42] Getting service log rke2
I0430 11:33:39.036852    8536 log.go:42] Getting service log cos-setup-boot
I0430 11:33:39.053409    8536 log.go:42] Getting service log cos-setup-fs
I0430 11:33:39.068132    8536 log.go:42] Getting service log cos-setup-initramfs
I0430 11:33:39.085935    8536 log.go:42] Getting service log cos-setup-network
I0430 11:33:39.101440    8536 log.go:42] Getting service log cos-setup-reconcile
I0430 11:33:39.119528    8536 log.go:42] Getting service log cos-setup-rootfs
I0430 11:33:39.136151    8536 log.go:42] Getting service log cos-immutable-rootfs
I0430 11:33:39.153850    8536 log.go:42] Getting service log elemental
I0430 11:33:39.170564    8536 log.go:42] Getting service log NetworkManager
I0430 11:33:39.190169    8536 log.go:42] Getting elemental-cli version
I0430 11:33:39.205410    8536 log.go:42] Getting elemental-operator version
I0430 11:33:39.205621    8536 log.go:42] Getting elemental-register version
I0430 11:33:39.266263    8536 log.go:42] Found k3s kubeconfig at /etc/rancher/k3s/k3s.yaml
I0430 11:33:39.266312    8536 log.go:42] Found k3s kubectl at /usr/local/bin/kubectl
I0430 11:33:39.266320    8536 log.go:42] Getting k8s info for pods
I0430 11:33:39.770730    8536 log.go:42] Getting k8s info for secrets
I0430 11:33:39.962037    8536 log.go:42] Getting k8s info for nodes
I0430 11:33:40.118680    8536 log.go:42] Getting k8s info for services
I0430 11:33:40.280797    8536 log.go:42] Getting k8s info for deployments
I0430 11:33:40.458869    8536 log.go:42] Getting k8s info for plans
I0430 11:33:40.612138    8536 log.go:42] Getting k8s info for apps
I0430 11:33:40.787309    8536 log.go:42] Getting k8s info for jobs
I0430 11:33:40.932361    8536 log.go:42] Getting k8s logs for namespace cattle-system
I0430 11:33:41.353556    8536 log.go:42] Getting k8s logs for namespace kube-system
I0430 11:33:41.935885    8536 log.go:42] Getting k8s logs for namespace ingress-nginx
W0430 11:33:41.999345    8536 log.go:62] No pods in namespace ingress-nginx
I0430 11:33:41.999365    8536 log.go:42] Getting k8s logs for namespace calico-system
W0430 11:33:42.061902    8536 log.go:62] No pods in namespace calico-system
I0430 11:33:42.061927    8536 log.go:42] Getting k8s logs for namespace cattle-fleet-system
I0430 11:33:42.204459    8536 log.go:42] Creating final file
I0430 11:33:42.215815    8536 log.go:42] All done. File created at m-993369ec-4b3f-4368-86c3-1449ebf57cf2-2024-04-30T113342Z.tar.gz
----
