= Backup
:revdate: 06-11-2025
:page-revdate: {revdate}

Como {elemental-product-name} é executado como parte do Rancher, os recursos {elemental-product-name} estão agrupados no backup do Rancher.
Para mais detalhes sobre backups do Rancher, restauração e opções de recuperação de desastres, siga a https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.html[documentação oficial do Rancher].

== Instale o operador rancher-backup para o Rancher

Siga o https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up.html[guia de backup do Rancher] para aprender a instalar e configurar o operador de backup do Rancher.


== Faça backup de {elemental-product-name} com o operador rancher-backup

Crie um `backup object` (adaptado às suas necessidades) para backup do Rancher em execução em um cluster Kubernetes.

[,yaml]
----
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: rancher-backup
spec:
  resourceSetName: rancher-resource-set
  schedule: "10 3 * * *"
  retentionCount: 10
----

O operador rancher-backup oferece várias opções para agendamento, criptografia e classes de armazenamento.
Você pode explorar todas as opções lendo a https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.html[documentação oficial].

Verifique os logs do operador rancher-backup.

[,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

Verifique se o arquivo de backup foi criado no Volume Persistente.

[,shell]
----
...
INFO[2022/10/17 07:45:04] Finding files starting with /var/lib/backups/rancher-backup-430169aa-edde-4a61-85e8-858f625a755b*.tar.gz
INFO[2022/10/17 07:45:04] File rancher-backup-430169aa-edde-4a61-85e8-858f625a755b-2022-10-17T05-15-00Z.tar.gz was created at 2022-10-17 0
...
----
