= Configure os endereĂ§os IP internos e externos do K3s e RKE2
:revdate: 2025-09-08
:page-revdate: {revdate}

K3s e RKE2 permitem especificar os endereĂ§os IP internos e externos de um nĂł atravĂ©s dos parĂąmetros `--node-ip` e `--node-external-ip`.

O Provisionamento do Rancher permite preencher esses parĂąmetros coletando o endereĂ§o IP de cada interface de rede do nĂł.

De qualquer forma, os mĂ©todos para coletar essas opĂ§Ă”es de IP para Clusters Rancher _Custom_ e _Elemental_ diferem.

== ConfiguraĂ§ĂŁo dos endereĂ§os IP internos e externos do K3s e RKE2 no provisionamento de Clusters Rancher

O provisionamento do Rancher permite especificar na seĂ§ĂŁo do Agente Rancher as interfaces de rede que devem ser vinculadas aos endereĂ§os IP internos e externos de cada nĂł provisionado.

Isso Ă© realizado adicionando os nomes das interfaces de rede das quais os endereĂ§os IP devem ser extraĂ­dos nas VariĂĄveis de Ambiente do Agente `CATTLE_INTERNAL_ADDRESS` e `CATTLE_ADDRESS` (https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/rancher-agent-options#ip-address-options[veja a documentaĂ§ĂŁo do Rancher]).

[NOTE]
====
As VariĂĄveis de Ambiente do Agente `CATTLE_INTERNAL_ADDRESS` e `CATTLE_ADDRESS` podem ser preenchidas diretamente com os endereĂ§os IP desejados. De qualquer forma, uma vez que os endereĂ§os IP internos e externos sĂŁo _por nĂł_, isso nĂŁo funcionaria exceto para clusters de nĂł Ășnico.
====


[CAUTION]
====
Enquanto durante a criaĂ§ĂŁo de um Cluster Elemental Ă© possĂ­vel adicionar VariĂĄveis de Ambiente do Agente, as `CATTLE_ADDRESS` e `CATTLE_INTERNAL_ADDRESS` sĂŁo ignoradas e nĂŁo resultariam na configuraĂ§ĂŁo dos endereĂ§os IP internos e externos dos nĂłs provisionados.
====


== Configure os endereĂ§os IP internos e externos do K3s e RKE2 em Clusters Elementais

Elemental permite configurar os endereĂ§os IP internos e externos dos NĂłs do Cluster anexando os rĂłtulos `elemental.cattle.io/InternalIP` e `elemental.cattle.io/ExternalIP` aos recursos xref:references/machineinventory-reference.adoc[MachineInventory] que rastreiam os nĂłs-alvo.

Esses rĂłtulos, quando anexados a um recurso xref:references/machineinventory-reference.adoc[MachineInventory], sĂŁo usados para preencher os endereĂ§os IP internos e externos dos nĂłs associados.

Os rĂłtulos podem ser adicionados aos campos xref:references/machineregistration-reference.adoc[MachineRegistration] `machineInventoryLabels`, usando as variĂĄveis de endereĂ§o IP do xref:label-templates/label-templates-network.adoc[Network Label Template] como valores, a fim de permitir a coleta dos endereĂ§os IP de cada nĂł.

Exemplo: xref:references/machineregistration-reference.adoc[MachineRegistration] onde os nĂłs terĂŁo o endereĂ§o IP interno definido a partir da interface eth0 e o endereĂ§o IP externo a partir da eth1.

.registration.yaml
[,yaml]
----
include::example$labeltemplates/registration.yaml[]
----
