= Restaurar
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-09-08
:page-revdate: {revdate}

Siga este guia para restaurar uma {elemental-product-name} configuração a partir de um backup com Rancher.

== Prepare o operador rancher-backup e os arquivos de backup para a restauração.

Acesse a https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher[documentação oficial do Rancher] e certifique-se de que `rancher-backup operator` está instalado e tem acesso aos arquivos de backup.

Primeiro, você deve seguir esta xref:operator-operational-tasks/backup.adoc[documentação] para fazer um backup dos recursos {elemental-product-name}.

== Restaure a configuração {elemental-product-name} com o operador rancher-backup.

Crie um `restore object` (adaptado às suas necessidades) para restaurar o arquivo tarball de backup.

[,yaml]
----
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: elemental-restore
spec:
  backupFilename: rancher-backup-430169aa-edde-4a61-85e8-858f625a755b-2022-10-17T05-15-00Z.tar.gz
----

Aplique o manifesto no Kubernetes.

[,shell]
----
kubectl apply -f elemental-restore.yaml
----

Verifique os logs do operador rancher-backup.

[,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

Verifique se o arquivo de backup foi restaurado com sucesso.

[,shell]
----
...
INFO[2022/10/31 06:34:50] Processing controllerRef apps/v1/deployments/rancher
INFO[2022/10/31 06:34:50] Done restoring
...
----

Continue com o procedimento da https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster[documentação do Rancher].
