= Registrar um SO nĂŁo gerenciado
:revdate: 2025-09-08
:page-revdate: {revdate}

Normalmente, o {elemental_operator_url}[{elemental_operator_name}] gerencia sistemas operacionais que sĂŁo instalados e configurados pelo {elemental_toolkit_url}[{elemental_toolkit_name}]. +
Por exemplo, para automatizar a instalaĂ§ĂŁo, fazer upgrade e redefiniĂ§ĂŁo do SO, o `elemental-register` depende do `elemental` CLI para executar essas operaĂ§Ă”es.

No entanto, tambĂ©m Ă© possĂ­vel registrar e provisionar {elemental-product-name} sistemas "sem toolkit".

Nesse cenĂĄrio, xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_register_command_line_tool[elemental-register] precisa ser instalado no sistema. +
Opcionalmente, o xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] pode ser instalado. Observe que sem o `elemental-system-agent`, o {elemental_operator_name} nĂŁo poderĂĄ provisionar nenhum cluster k8s na mĂĄquina. Nesse caso, o {elemental_operator_name} sĂł pode ser usado para fins de inventĂĄrio do SO.

Finalmente, no cluster de gerenciamento, o `MachineRegistration` deve habilitar a flag `spec.config.elemental.registration.no-toolkit`.

Uma vez que `no-toolkit` estĂĄ habilitado no `MachineRegistration`, e um novo registro ocorre usando `elemental-register --install` no sistema, um novo `MachineInventory` serĂĄ criado no cluster de gerenciamento:

[,bash]
----
kubectl -n fleet-default describe machineinventory my-unmanaged-os-machine
----

O `MachineInventory` serĂĄ anotado com a anotaĂ§ĂŁo `elemental.cattle.io/os.unmanaged: "true"`, destacando que esta mĂĄquina nĂŁo Ă© gerenciada e tem funcionalidade limitada.

No sistema, apĂłs o registro bem-sucedido, os arquivos `/etc/rancher/elemental/agent/config.yaml` e `/var/lib/elemental/agent/elemental_connection.json` sĂŁo criados automaticamente para configurar o `elemental-system-agent`.
O componente `elemental-system-agent` Ă© necessĂĄrio para o provisionamento do K8s e gatilhos de redefiniĂ§ĂŁo.

Quando um xref:node-operational-tasks/reset.adoc[machine reset] Ă© acionado, por exemplo, ao excluir o `MachineInventory` diretamente, o `elemental-system-agent` executarĂĄ um plano de redefiniĂ§ĂŁo simples que criarĂĄ o arquivo sentinela `/var/lib/elemental/.unmanaged_reset`. +
A presenĂ§a deste arquivo indica que a mĂĄquina precisa de uma redefiniĂ§ĂŁo. Isso pode envolver a parada de serviĂ§os, desinstalaĂ§ĂŁo de pacotes, formataĂ§ĂŁo de dispositivos, e assim por diante, dependendo de como a mĂĄquina Ă© gerenciada customizadamente.

== Recursos suportados

* Registro de um `MachineInventory`
* Provisionamento do K8s (quando o xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] estĂĄ instalado e em execuĂ§ĂŁo na mĂĄquina)
* Gatilhos de redefiniĂ§ĂŁo (quando o xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] estĂĄ instalado e em execuĂ§ĂŁo na mĂĄquina)

== Recursos nĂŁo suportados

* xref:references/cloud-config-reference.adoc[ConfiguraĂ§ĂŁo] impulsionada pelo Cloud-init.
* SO xref:node-operational-tasks/upgrade.adoc[Fazer upgrade]
* SO xref:node-operational-tasks/reset.adoc[RedefiniĂ§ĂŁo]
