= Incorporación de máquinas
:revdate: 6/11/2025
:page-revdate: {revdate}

El objetivo del servicio de Incorporación de Máquinas es registrar una nueva máquina en el catálogo del {elemental-product-name} Operador (xref:references/machineinventory-reference.adoc[InventarioDeMáquinas] recursos) y aprovisionar el host con el sistema operativo, aplicando la configuración deseada.

La Incorporación de Máquinas implica los siguientes pasos:

* El usuario crea un recurso xref:references/machineregistration-reference.adoc[RegistroDeMáquina]: el RegistroDeMáquina incluye la configuración necesaria para la instalación del sistema operativo.
Tan pronto como se crea el RegistroDeMáquina, el {elemental-product-name} Operador expone un HTTP _punto de registro_: es el punto de entrada requerido por los hosts de incorporación para registrarse en el operador.
* El usuario solicita una imagen de auto-instalación a través de un recurso xref:references/seedimage-reference.adoc[ImagenSemilla]: solo requiere una referencia a un recurso de RegistroDeMáquina y a una imagen de contenedor de sistema operativo compatible con el {elemental-product-name} Toolkit.
Tan pronto como se crea la ImagenSemilla, el {elemental-product-name} Operador activa el proceso de construcción del recurso de auto-instalación image: once completed, the URL is exposed in the `status.downloadURL` field of the xref:references/seedimage-reference.adoc[ImagenSemilla].
* El usuario descarga la imagen de auto-instalación y la utiliza para arrancar un host no aprovisionado: el host https://documentation.suse.com/cloudnative/os-manager/latest/en/rancher-os-management/authentication.html[se autentica] en el _punto de registro_ del {elemental-product-name} Operador, obtiene la configuración completa almacenada en el RegistroDeMáquina e instala el sistema operativo en el dispositivo de almacenamiento local. Tan pronto como el host ha completado el proceso de registro, el {elemental-product-name} Operador crea un recurso único xref:references/machineinventory-reference.adoc[InventarioDeMáquinas] que rastrea el host.
La imagen de auto-instalación puede ser utilizada para incorporar cualquier número de hosts.
