= Enregistrer un système d'exploitation non géré
:revdate: 2025-09-08
:page-revdate: {revdate}

Normalement, le {elemental_operator_url}[{elemental_operator_name}] gère les systèmes d'exploitation qui sont installés et configurés par le {elemental_toolkit_url}[{elemental_toolkit_name}]. +
Par exemple, pour automatiser l'installation, la mise à niveau et la réinitialisation du système d'exploitation, le `elemental-register` s'appuie sur la CLI `elemental` pour exécuter ces opérations.

Cependant, il est également possible d'enregistrer et de provisionner des systèmes {elemental-product-name} "sans boîte à outils".

Dans ce scénario, xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_register_command_line_tool[elemental-register] doit être installé sur le système. +
En option, le xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] peut être installé. Notez qu'en l'absence du `elemental-system-agent`, le {elemental_operator_name} ne pourra pas provisionner de cluster k8s sur la machine. Dans ce cas, le {elemental_operator_name} ne peut être utilisé qu'à des fins d'inventaire du système d'exploitation.

Enfin, sur le cluster de gestion, le `MachineRegistration` doit activer l'option `spec.config.elemental.registration.no-toolkit`.

Une fois que `no-toolkit` est activé sur le `MachineRegistration`, et qu'un nouvel enregistrement se produit en utilisant `elemental-register --install` sur le système, un nouveau `MachineInventory` sera créé sur le cluster de gestion :

[,bash]
----
kubectl -n fleet-default describe machineinventory my-unmanaged-os-machine
----

Le `MachineInventory` sera annoté avec l'annotation `elemental.cattle.io/os.unmanaged: "true"`, soulignant que cette machine n'est pas gérée et a des fonctionnalités limitées.

Sur le système, après un enregistrement réussi, les fichiers `/etc/rancher/elemental/agent/config.yaml` et `/var/lib/elemental/agent/elemental_connection.json` sont automatiquement créés pour configurer le `elemental-system-agent`.
Le composant `elemental-system-agent` est nécessaire pour le provisionnement K8s et les déclencheurs de réinitialisation.

Lorsqu'une xref:node-operational-tasks/reset.adoc[machine reset] est déclenchée, par exemple en supprimant directement le `MachineInventory`, le `elemental-system-agent` exécutera un plan de réinitialisation simple qui créera le fichier sentinelle `/var/lib/elemental/.unmanaged_reset`. +
La présence de ce fichier indique que la machine a besoin d'une réinitialisation. Cela peut impliquer l'arrêt des services, la désinstallation de paquets, le formatage des dispositifs, etc., selon la manière dont la machine est gérée de manière personnalisée.

== Fonctionnalités prises en charge

* Enregistrement d'un `MachineInventory`
* Provisionnement K8s (lorsque le xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] est installé et en cours d'exécution sur la machine)
* Déclencheurs de réinitialisation (lorsque le xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] est installé et en cours d'exécution sur la machine)

== Fonctionnalités non prises en charge

* xref:references/cloud-config-reference.adoc[Configuration] pilotée par Cloud-init
* Mises à niveau xref:node-operational-tasks/upgrade.adoc[du système d'exploitation]
* Réinitialisation xref:node-operational-tasks/reset.adoc[du système d'exploitation]
