= SUSE® Rancher Prime OS Manager Operator Helm Chart

The {elemental_operator_url}[{elemental_operator_name}] is responsible for managing the SUSE® Rancher Prime OS Manager versions and maintaining a machine inventory to assist with edge or bare metal installations.

The associated chart bootstraps an elemental-operator deployment on the https://rancher.com/docs/rancher/v2.6/[Rancher Manager v2.6] cluster using the https://helm.sh[Helm] package manager.

== Prerequisites

* Rancher Manager version v2.6
* Helm client version v3.8.0+

== Get Helm chart info

[,console]
----
helm pull oci://registry.suse.com/rancher/elemental-operator-chart
helm show all oci://registry.suse.com/rancher/elemental-operator-chart
----

== Install Chart

[,console]
----
helm install --create-namespace -n cattle-elemental-system elemental-operator-crds \
             oci://registry.suse.com/rancher/elemental-operator-crds-chart
helm install --create-namespace -n cattle-elemental-system elemental-operator \
             oci://registry.suse.com/rancher/elemental-operator-chart
----

The command deploys elemental-operator on the Kubernetes cluster in the default configuration.

_See <<_configuration,configuration>> below._

_See https://helm.sh/docs/helm/helm_install/[helm install] for command documentation._

== Uninstall Chart

[,console]
----
helm uninstall -n cattle-elemental-system elemental-operator
----

This removes all the Kubernetes components associated with the chart and deletes the release.

_See https://helm.sh/docs/helm/helm_uninstall/[helm uninstall] for command documentation._

== Upgrading Chart

[,console]
----
helm upgrade -n cattle-elemental-system \
             --install elemental-operator \
             oci://registry.suse.com/rancher/elemental-operator-chart
----

_See https://helm.sh/docs/helm/helm_upgrade/[helm upgrade] for command documentation._

== Configuration

See https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing[Customizing the Chart Before Installing]. To see all configurable options with detailed comments, visit the chart's <<_values,values>>, or run these configuration commands:

`console showLineNumbers
helm show values oci://registry.suse.com/rancher/elemental-operator-chart
`

== Values

[cols="2,1,2,2"]
|===
| Key | Type | Default | Description

| image.empty | string | `rancher/pause:3.1` |  

| image.repository | string | `registry.suse.com/rancher/elemental-operator-chart` | Source image for elemental-operator with repository name  

| image.tag | tag | `""` |  

| image.imagePullPolicy | string | `IfNotPresent` |  

| noProxy | string | `127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local` | Comma separated list of domains or ip addresses that will not use the proxy 

| global.cattle.systemDefaultRegistry | string | `""` | Default container registry name  

| sync_interval | string | `"60m"` | Default sync interval for upgrade channel 

| sync_namespaces | list | `[]` | Namespace the operator will watch for, leave empty for all 

| debug | bool | `false` | Enable debug output for operator 

| nodeSelector.kubernetes.io/os | string | `linux` |  

| tolerations | object | `{}` |  

| tolerations.key | string | `cattle.io/os` |  

| tolerations.operator | string | `"Equal"` |  

| tolerations.value | string | `"linux"` |  

| tolerations.effect | string | `NoSchedule` |  
|===
