= Architecture Components
:revdate: 2025-07-03
:page-revdate: {revdate}

The components required to provide the xref:architecture-services.adoc[{elemental-product-name} services] are:

* the <<_elemental_command_line_tool,`elemental`>> command line tool
* the <<_elemental_operator_daemon,`elemental-operator`>> daemon
* the <<_elemental_register_command_line_tool,`elemental-register`>> command line tool
* the <<_elemental_system_agent_daemon,`elemental-system-agent`>> daemon
* one or more <<_suse_rancher_prime_os_manager_os_container_image,{elemental-product-name} OS container images>>

== `elemental` command line tool

The `elemental` tool is part of the link:{elemental_toolkit_url}[{elemental_toolkit_name}] project.
It performs the actual OS installation and upgrade operations on the host and is used to execute the xref:cloud-config-reference.adoc[cloud-config] directives added in the xref:custom-resources.adoc[{elemental-product-name} CRDs].

The `elemental` binary is included in all the base OS images distributed with {elemental-product-name}.

== `elemental-operator` daemon

The *elemental-operator* daemon performs two main tasks:

. embeds the {elemental-product-name} Kubernetes controllers to manage all the xref:custom-resources.adoc[{elemental-product-name} CRDs]
. exposes the _registration endpoints_ to allow the host to register and download the OS installation configuration during the xref:architecture-machineonboarding.adoc[machine onboarding]

The `elemental-operator` daemon is deployed on the Rancher cluster as a `Deployment` via the xref:operatorchart-reference.adoc[{elemental-product-name} Operator Helm Chart].

== `elemental-register` command line tool

The *elemental-register* binary is the client used to register the host against the _registration endpoints_ exposed by the <<_elemental_operator_daemon,elemental-operator>>. It collects and forwards the host data to allow the <<_elemental_operator_daemon,elemental-operator>> to fill the SMBIOS and the Hardware label templates.

If the registraton phase is performed successfully, the *elemental-register* gets the full configuration stored in the xref:machineregistration-reference.adoc[MachineRegistration] from the *elemental-operator*.
As the last step, the *elemental-register* client calls the <<_elemental_command_line_tool,elemental>> binary passing the retrieved configuration to kick off the OS installation.

== `elemental-system-agent` daemon

The `elemental-system-agent` is built from the https://github.com/rancher/system-agent[Rancher System Agent project] and allows {elemental-product-name} to deploy _plans_ to assist with the host provisioning.
Notably, the `rancher-system-agent` installation and configuration required for the xref:architecture-clusterdeployment.adoc[Kubernetes Cluster provisioning service] is performed through an `elemental-system-agent` _plan_.

== {elemental-product-name} OS container image

An link:{elemental_toolkit_url}[{elemental_toolkit_name}] OS image is an OCI container image containing all the files that will make up the OS of the target host. It contains not only all the binaries and libraries, but also the kernel and the boot files required by a linux system.

The {elemental-product-name} OS image is an opinionated link:{elemental_toolkit_url}[{elemental_toolkit_name}] OS image which is based on https://www.suse.com/products/micro/[SLE Micro] and contains specific {elemental-product-name} configurations and binaries (the <<_elemental_command_line_tool,elemental>> and the <<_elemental_register_command_line_tool,elemental-register>> ones).

The {elemental-product-name} OS images are tracked in the xref:managedosversion-reference.adoc[ManagedOSVersions] resources. The xref:managedosversion-reference.adoc[ManagedOSVersions] resources are dynamically created from xref:managedosversionchannel-reference.adoc[ManagedOSVersionChannel] resources. A defaultxref:managedosversionchannel-reference.adoc[ManagedOSVersionChannel] resource is deployed with each {elemental-product-name} Operator installation.
