= インベントリ管理
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-08-15
:page-revdate: {revdate}

{elemental-product-name}オペレーターは、機械の在庫とその機械の設定および割り当てられたクラスターとのマッピングを保持できます。

== MachineInventory

`MachineInventory`は、登録された機械に関するすべての関連情報を保持します。 +
登録が成功すると、`MachineInventory`は関連する`machineInventoryLabels`で定義されたすべての`MachineRegistration`を継承します。 +
さらに、機械`annotations`は、各成功した登録時に更新されます。

デフォルトでは、{elemental-product-name}機械はラベルと注釈を更新するために、24時間ごとに登録を更新することを試みます。

=== リファレンス

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  # Machine annotations can be useful to identify hosts
  annotations:
    elemental.cattle.io/auth: tpm
    elemental.cattle.io/registration-ip: 192.168.122.152
  labels:
    # A label inherited from the MachineRegistration definition
    element: fire
    # Generic SMBIOS labels that are typically populated with
    # the MachineRegister approach
    machineUUID: f266c64b-3972-40e7-9937-3dc4a311436c
    manufacturer: QEMU
    productName: Standard-PC-Q35-ICH9-2009
    serialNumber: Not-Specified
    # Custom labels can be applied to each MachineInventory
    myCustomLabel: foo
  name: m-479ab68e-00ff-4081-a731-5b1a76610289
  # The namespace must match the namespace of the cluster
  # assigned to the clusters.provisioning.cattle.io resource
  namespace: fleet-default
  # A reference to the MachineInventorySelector that links the
  # machine to a Cluster definition
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: MachineInventorySelector
    name: fire-machine-selector-qcn7d
    uid: 0a1f751e-4ca9-4a0d-919a-97ba1f434d12
spec:
  # The hash of the TPM EK public key. This is used if you are
  # using TPM2 to identify nodes. Nodes can report their TPM
  # hash by using the MachineRegistration.
  tpmHash: d68795c6192af9922692f050b...
----

== MachineRegistration

`MachineRegistration`は、すべての接続された{elemental-product-name}機械のインストール、リセット、および設定方法に関する情報を保持します。

`spec.machineInventoryLabels`と`spec.machineInventoryAnnotations`を更新することが可能であり、これはすべての登録された機械に適用されます。
デフォルトでは、{elemental-product-name}機械はラベルと注釈を更新するために、24時間ごとに登録を更新することを試みます。

`spec.config`定義を変更することは可能ですが、インストールを完了した機械は`spec.config`への更新を無視します。
インストールを完了できなかった機械は、リモート`MachineRegistration`定義を再読み込みすることで、30分ごとに再試行します。これは、成功したインストールを妨げる`spec.config`の誤り（例：`spec.config.elemental.install.device`）を修正するのに役立ち、新しい`MachineRegistration`や新しい.isoを作成する必要がありません。

=== リファレンス

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  # The namespace must match the namespace of the cluster
  # assigned to the clusters.provisioning.cattle.io resource
  namespace: fleet-default
spec:
  # The cloud config that will be used to provision the node
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
      reset:
        enabled: true
        debug: true
        reset-persistent: true
        reset-oem: true
        reboot: true
  # Labels to be added to the created MachineInventory object
  machineInventoryLabels:
    element: fire
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
  # Annotations to be added to the created MachineInventory object
  machineInventoryAnnotations: {}
----
